# WordPress Test Matrix for Plugin
# https://github.com/thingsym/wordpress-test-matrix

sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=5.1 WP_MULTISITE=0
  - WP_VERSION=5.1 WP_MULTISITE=1
  - WP_VERSION=5.0 WP_MULTISITE=0
  - WP_VERSION=5.0 WP_MULTISITE=1
  - WP_VERSION=4.9 WP_MULTISITE=0
  - WP_VERSION=4.9 WP_MULTISITE=1
  - WP_VERSION=4.8 WP_MULTISITE=0
  - WP_VERSION=4.8 WP_MULTISITE=1
  - WP_VERSION=4.7 WP_MULTISITE=0
  - WP_VERSION=4.7 WP_MULTISITE=1
  - WP_VERSION=4.6 WP_MULTISITE=0
  - WP_VERSION=4.6 WP_MULTISITE=1
  - WP_VERSION=4.5 WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=1
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=4.4 WP_MULTISITE=1
  - WP_VERSION=nightly WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=1
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0
  - WP_VERSION=3.9 WP_MULTISITE=0
  # Wordpress Requires at least: 3.9
  # - WP_VERSION=3.8 WP_MULTISITE=0
  # - WP_VERSION=3.7 WP_MULTISITE=0

matrix:
  fast_finish: true
  allow_failures:
    # WordPress 4.6 earlier not compatible with PHP 7.1.
    # Warning: Parameter 1 to wp_default_styles() expected to be a reference
    # https://core.trac.wordpress.org/ticket/37772
    - php: 7.1
      env: WP_VERSION=4.6 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.6 WP_MULTISITE=1
    - php: 7.1
      env: WP_VERSION=4.5 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.5 WP_MULTISITE=1
    - php: 7.1
      env: WP_VERSION=4.4 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.4 WP_MULTISITE=1
    - php: 7.1
      env: WP_VERSION=4.3 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.2 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=3.9 WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  # for WP_VERSION <= 4.6 due to PHP Fatal error: Class 'PHPUnit_Framework_TestCase' not found
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]] && [[ "$WP_VERSION" < 4.6* ]] ; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*|5.7.*|6.*"
    fi
  # disable WP_DEBUG for PHP >= 5.5 due to ext/mysqli E_DEPRECATED errors
  - |
    if [[ "$TRAVIS_PHP_VERSION" > 5.4* ]] && [[ "$WP_VERSION" == "3.6" ]] ; then
      sed -i "s:define( 'WP_DEBUG://define( 'WP_DEBUG:" /tmp/wordpress-tests-lib/wp-tests-config.php;
    fi
  - |
    if [[ "$TRAVIS_PHP_VERSION" > 5.4* ]] && [[ "$WP_VERSION" == "3.7" ]] ; then
      sed -i "s:define( 'WP_DEBUG://define( 'WP_DEBUG:" /tmp/wordpress-tests-lib/wp-tests-config.php;
    fi
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

script:
  - phpunit
